version: "3"

services:
  apache:
    build: ./docker/apache
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - 80:80
  mysql:
    build: ./docker/db
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    links:
      - mysql
    ports:
      - 8000:80
    volumes:
      - /sessions
